-- MySQL Script generated by MySQL Workbench
-- Sat Jan 16 20:22:21 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema encuestas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema encuestas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `encuestas` DEFAULT CHARACTER SET utf8 ;
USE `encuestas` ;

-- -----------------------------------------------------
-- Table `encuestas`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `rut` VARCHAR(45) NULL,
  `clave` VARCHAR(255) NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`clave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`clave` (
  `id_clave` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NULL,
  PRIMARY KEY (`id_clave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`encuesta` (
  `id_encuesta` INT NOT NULL AUTO_INCREMENT,
  `nombre_encuesta` VARCHAR(45) NULL,
  `tipo_encuesta` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NULL,
  `empresa_id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_encuesta`),
  INDEX `fk_encuesta_empresa1_idx` (`empresa_id_empresa` ASC),
  CONSTRAINT `fk_encuesta_empresa1`
    FOREIGN KEY (`empresa_id_empresa`)
    REFERENCES `encuestas`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`pregunta` (
  `id_pregunta` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(255) NULL,
  `fecha_creacion` DATETIME NULL,
  `encuesta_id_encuesta` INT NOT NULL,
  PRIMARY KEY (`id_pregunta`),
  INDEX `fk_pregunta_encuesta1_idx` (`encuesta_id_encuesta` ASC),
  CONSTRAINT `fk_pregunta_encuesta1`
    FOREIGN KEY (`encuesta_id_encuesta`)
    REFERENCES `encuestas`.`encuesta` (`id_encuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`respuesta_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`respuesta_tipo` (
  `id_respuesta_tipo` INT NOT NULL AUTO_INCREMENT,
  `respuesta` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `fecha_creacion` DATETIME NULL,
  `pregunta_id_pregunta` INT NOT NULL,
  PRIMARY KEY (`id_respuesta_tipo`),
  INDEX `fk_respuesta_tipo_pregunta1_idx` (`pregunta_id_pregunta` ASC),
  CONSTRAINT `fk_respuesta_tipo_pregunta1`
    FOREIGN KEY (`pregunta_id_pregunta`)
    REFERENCES `encuestas`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`respuesta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`respuesta_usuario` (
  `id_respuesta_usuario` INT NOT NULL AUTO_INCREMENT,
  `respuesta` INT NULL,
  `estado` INT NULL,
  `comentario` VARCHAR(255) NULL,
  `fecha_creacion` DATETIME NULL,
  `respuesta_tipo_id_respuesta_tipo` INT NOT NULL,
  PRIMARY KEY (`id_respuesta_usuario`),
  INDEX `fk_respuesta_usuario_respuesta_tipo1_idx` (`respuesta_tipo_id_respuesta_tipo` ASC),
  CONSTRAINT `fk_respuesta_usuario_respuesta_tipo1`
    FOREIGN KEY (`respuesta_tipo_id_respuesta_tipo`)
    REFERENCES `encuestas`.`respuesta_tipo` (`id_respuesta_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`comentario` (
  `id_comentario` INT NOT NULL,
  `comentario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_comentario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encuestas`.`encuesta_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encuestas`.`encuesta_has_usuario` (
  `encuesta_id_encuesta` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `estado` INT NULL,
  `fecha` DATETIME NULL,
  `comentario_id_comentario` INT NOT NULL,
  PRIMARY KEY (`encuesta_id_encuesta`, `usuario_id_usuario`),
  INDEX `fk_encuesta_has_usuario_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_encuesta_has_usuario_encuesta1_idx` (`encuesta_id_encuesta` ASC),
  INDEX `fk_encuesta_has_usuario_comentario1_idx` (`comentario_id_comentario` ASC),
  CONSTRAINT `fk_encuesta_has_usuario_encuesta1`
    FOREIGN KEY (`encuesta_id_encuesta`)
    REFERENCES `encuestas`.`encuesta` (`id_encuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuesta_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `encuestas`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuesta_has_usuario_comentario1`
    FOREIGN KEY (`comentario_id_comentario`)
    REFERENCES `encuestas`.`comentario` (`id_comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
